### ISSUE TITLE
iFrame content below-the-fold not rendered

### ISSUE THREAD

**Issue by arichter83** [PierBover/ios-iframe-fix#5]
Hi there!

also thank you from my side, this has been a light in a dark long investigation.

But I came accross a bug, that the content of an iFrame below the fold is not rendered anymore. I documented it in detail on StackOverflow:
https://stackoverflow.com/questions/55068656/safari-mobil-iframe-content-out-of-view-not-rendered

Do you have any idea or solution for this?

Thank you a lot,
Andreas

**Comment by PierBover** [comment]
The iframe implementation in Safari is completely broken. I've reported a number of bugs to Apple in the past years but either the Webkit team does not have enough resources to fix them or they do not want to.

Maybe there is a solution to your particular problem, but my recommendation would be to steer away from using iframes in iOS. Even if you fix your problem, the solution could break in the future.

**Comment by arichter83** [comment]
Thanks @PierBover for your prompt answer. Unfortunately I won't be able to steer away, as I am building a widget.

But luckily I found a solution today:

```
  #wrap {
    overflow-y: scroll;
    height: 100%;
    -webkit-overflow-scrolling: touch;
  }
```

It fixes the iFrame height extension without the `position:fixed` - works well for my case. I'll keep updating: https://stackoverflow.com/questions/55068656/safari-mobil-iframe-content-out-of-view-not-rendered
